export const GET_PROFILE_INITIAL = "GET_PROFILE_INITIAL";
export const GET_PROFILE_INITIAL_SUCCESS = "GET_PROFILE_INITIAL_SUCCESS";
export const GET_PROFILE_INITIAL_FAILED = "GET_PROFILE_INITIAL_FAILED";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";