export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";

export const REFRESH_SESSION_REQUEST = "REFRESH_SESSION_REQUEST";
export const REFRESH_SESSION_SUCCESS = "REFRESH_SESSION_SUCCESS";
export const REFRESH_SESSION_FAILED = "REFRESH_SESSION_FAILED";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const PASSWORD_TOKEN_REQUEST = "PASSWORD_TOKEN_REQUEST";
export const PASSWORD_TOKEN_SUCCESS = "PASSWORD_TOKEN_SUCCESS";
export const PASSWORD_TOKEN_FAILED = "PASSWORD_TOKEN_FAILED";

export const PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED";

export const VALIDATE_FORM = "VALIDATE_FORM";
